In [1]:
import numpy as np

In [2]:
# normalize
arr=np.array([[1,2],[3,4]])
mean=np.mean(arr)
std_dev=np.std(arr)
normalized_arr=(arr-mean)/std_dev
print(normalized_arr)
print(mean)
print(std_dev)
print(np.sqrt(5/4))

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
1.118033988749895


In [3]:
# mathematical fnx
# aggregation

arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [4]:
# power fnx
arr=np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [5]:
# log &exponential
arr=np.array([1,2,3,4,5])

print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [6]:
# rounding
arr=np.array([1,2,3,4,5,2,3,1,-8,-9,-3])
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

3.0
4.0
3.0
3.0
[-9 -8 -3  1  2  3  4  5]
[-9 -8 -3  1  1  2  2  3  3  4  5]
[1 2 3 4 5 2 3 1 8 9 3]
