In [1]:
import numpy as np

In [2]:
# properties
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)     #dimension = m * n
print(arr.size)     #tot els - 9
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)


(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [3]:
# opretion on array
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped=arr.reshape((3,2))
print(reshaped,reshaped.shape)

flattened=arr.flatten()
print(flattened,flattened.shape)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [4]:
# indexing
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1[0][2])

arr=np.array([1,2,3,4,5,6,7])

print(arr[0])
print(arr[1])

# fency indexing
idx=[0,1,3]
print(arr[idx])

# boolean indexing
print(arr[arr>4])
print(arr[arr % 2 != 0])
print(arr[arr % 2 == 0])


3
1
2
[1 2 4]
[5 6 7]
[1 3 5 7]
[2 4 6]


In [5]:
# slicing
arr9=np.array([1,2,3,4,5])
print(arr9[1:4])
print(arr9[1:])
print(arr9[:6])
print(arr9[1::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4 5]
[2 4]
