In [1]:
import numpy as np

In [2]:
# copy vs view
arr=[1,2,3,4,5] # list

#It creat copy of list
sub_arr=arr[1:5]
sub_arr[2]=100
print(arr)
print(sub_arr)

arr1=np.array(arr) # array

#It creat view of array(while copy isn't use )
sub_arr1=arr1[1:5]
sub_arr2=arr1[1:5].copy()    #to create a copy
sub_arr1[2]=200
print(arr1)
print(sub_arr1)

[1, 2, 3, 4, 5]
[2, 3, 100, 5]
[  1   2   3 200   5]
[  2   3 200   5]


In [3]:
# multi_dimensional arrays
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]]) # 2D array
print(arr2D)

print(np.sum(arr2D))

sum_of_columns=np.sum(arr2D,axis=0)
print(sum_of_columns)

sum_of_raw=np.sum(arr2D,axis=1)
print(sum_of_raw)

print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [4]:
#3D array
arr3D =np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])

print(arr3D,arr3D.shape)

# indexing
print(arr3D[0,1,1])

# slicing
arr3D[:,0,:] # first row from both layers
arr3D[:,:,1] # second columnfrom both layers

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4


array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [5]:
# vectorization
arr1 =np.array([1,2,3,4,5])
arr2=np.array([1,2,3,4,5])
print(arr1 + arr2)

[ 2  4  6  8 10]


In [6]:
# broadcasting
arr =np.array([1,2,3,4,5])
arr1=np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(arr + 5)

print(arr.shape)

print(arr1.shape)

print(arr+arr1)

[ 6  7  8  9 10]
(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
