In [1]:
import numpy as np
import time

In [2]:
# execution performance
size=1_00_000

#python list 
py_list=list(range(size))
start=time.time()
sq_list=[x**2 for x in py_list]
end=time.time()
print(f"python list time={end-start}second")

# numpy arrays
nump_arr=np.array(py_list)
start=time.time()
sq_np_list=nump_arr**2
end = time.time()
print(f"numpy array time={end-start}second")

python list time=0.021795272827148438second
numpy array time=0.0016317367553710938second


In [3]:
# memory
import sys 

print(f"size 0f python list={sys.getsizeof(py_list)*len(py_list)} bytes")

print(f"size 0f numpy array={nump_arr.nbytes} bytes")

size 0f python list=80005600000 bytes
size 0f numpy array=800000 bytes


In [4]:
# create - from lists
arr1=np.array([2,3,4,5,6,7])
print(arr1,type(arr1),arr1.shape)

arr2=np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2),arr2.shape)
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3,type(arr3),arr3.shape)

[2 3 4 5 6 7] <class 'numpy.ndarray'> (6,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3)


# create numpy arrays with buid-in function

In [5]:
arr1=np.zeros((2,4),dtype="int64")  #prefill
print(arr1,arr1.shape)

[[0 0 0 0]
 [0 0 0 0]] (2, 4)


In [6]:
arr2=np.ones((3,4))  #prefill
print(arr2,arr2.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] (3, 4)


In [7]:
arr3=np.full((3,3),101)  #prefill with val
print(arr3,arr3.shape)

[[101 101 101]
 [101 101 101]
 [101 101 101]] (3, 3)


In [8]:
arr4=np.eye(4)            #identity matrix
print(arr4,arr4.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)


In [9]:
arr5=np.arange(1,29,2)     #range elements
print(arr5,arr5.shape)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27] (14,)


In [10]:
arr6=np.linspace(1,20,5)     #evenly spaced arrays
print(arr6,arr6.shape,arr6.dtype)

[ 1.    5.75 10.5  15.25 20.  ] (5,) float64
